//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labQuiz_TARATHEP_ORA03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_no { get; set; }
        public string title_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public string department { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
